### ISSUE TITLE
[RNA GDC] Genome file no longer available 

### ISSUE THREAD

**Issue by amn34** [Biodepot-LLC/workflows#32]
In the Download genome files widget one of the files it tries to download is no longer available and causes the Generate Index widget to fail and generating the following error message

![image](https://user-images.githubusercontent.com/56467927/117497293-2c816a00-af2d-11eb-9e1b-77984d3c90dd.png)

![image](https://user-images.githubusercontent.com/56467927/117497575-85e99900-af2d-11eb-8967-769b9069e5d7.png)

The file may have been updated with a newer 2021 version. The available files are at the link below
https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/

**Comment by lhhunghimself** [comment]
It looks like they just re-organized the file directories. Can you make the change and test the workflow. If it runs then save the workflow and change the permissions from root and push up a pull request?
