### ISSUE TITLE
DNA-seq Biobambam2 widget bypasses by default

### ISSUE THREAD

**Issue by BryceNoFu** [Biodepot-LLC/workflows#43]
Biobambam2 widget is set to bypass by default. When using biobambam2 widget by itself, bam to fq conversion is unable to be converted due to the process being bypassed.

![image](https://user-images.githubusercontent.com/38656368/125874686-ce721e1b-00f3-4d95-9b8a-609a36836a2f.png)

Potential fix: In the parameters, include a label to allow users to choose to bypass the widget, and set the default to False.

**Comment by lhhunghimself** [comment]
Removed the default True from Biobambam widgets in the DNA-seq workflows.

**Comment by rgschmitz1** [comment]
It turns out that not setting the bypass flag just disabled the bypass option entirely, setting to 'False' instead of 'True' seems to keep bypass turned off by default but allows the start widget to toggle this option.

See pull request #45 for fix.
